export const productSeedData = [
  {
    title: "ASUS ROG Strix G16 Gaming Laptop",
    brand: "ASUS",
    category: "Gaming Laptops",
    description:
      "High-performance gaming laptop with a fast 165Hz display, RTX graphics, and a thermal design tuned for marathon gaming sessions.",
    price: 149999,
    currency: "INR",
    discountPrice: 139999,
    images: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Intel Core i7-13650HX" },
      { key: "Graphics", value: "NVIDIA GeForce RTX 4060 8GB" },
      { key: "Memory", value: "16GB DDR5 RAM" },
      { key: "Storage", value: "1TB NVMe SSD" },
      { key: "Display", value: "16-inch FHD+ 165Hz" },
    ],
    rating: 4.6,
    reviewCount: 842,
    buyLinks: [
      { label: "Amazon", url: "https://www.amazon.in/" },
      { label: "ASUS Store", url: "https://in.store.asus.com/" },
    ],
    source: "ASUS Store",
    stockStatus: "in_stock",
    tags: ["gaming", "laptop", "rtx4060", "high-refresh-rate"],
  },
  {
    title: "Lenovo Legion 5 Pro 16 Gaming Laptop",
    brand: "Lenovo",
    category: "Gaming Laptops",
    description:
      "Premium gaming laptop with a vivid 16-inch panel, strong RTX performance, and reliable cooling for competitive titles and creative work.",
    price: 164990,
    currency: "INR",
    discountPrice: 154990,
    images: [
      "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "AMD Ryzen 7 7745HX" },
      { key: "Graphics", value: "NVIDIA GeForce RTX 4070 8GB" },
      { key: "Memory", value: "16GB DDR5 RAM" },
      { key: "Storage", value: "1TB PCIe Gen4 SSD" },
      { key: "Display", value: "16-inch WQXGA 240Hz" },
    ],
    rating: 4.7,
    reviewCount: 615,
    buyLinks: [
      { label: "Flipkart", url: "https://www.flipkart.com/" },
      { label: "Lenovo", url: "https://www.lenovo.com/in/en/" },
    ],
    source: "Lenovo",
    stockStatus: "in_stock",
    tags: ["gaming", "legion", "rtx4070", "qhd"],
  },
  {
    title: "HP Omen 16 Gaming Laptop",
    brand: "HP",
    category: "Gaming Laptops",
    description:
      "Balanced gaming laptop offering strong thermal performance, immersive audio, and a color-accurate panel for games and content creation.",
    price: 139990,
    currency: "INR",
    discountPrice: 129990,
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Intel Core i7-13700HX" },
      { key: "Graphics", value: "NVIDIA GeForce RTX 4050 6GB" },
      { key: "Memory", value: "16GB DDR5 RAM" },
      { key: "Storage", value: "1TB SSD" },
      { key: "Display", value: "16.1-inch FHD 144Hz" },
    ],
    rating: 4.4,
    reviewCount: 473,
    buyLinks: [
      { label: "Amazon", url: "https://www.amazon.in/" },
      { label: "HP Online Store", url: "https://www.hp.com/in-en/shop/" },
    ],
    source: "HP Online Store",
    stockStatus: "in_stock",
    tags: ["gaming", "omen", "intel", "144hz"],
  },
  {
    title: "Acer Nitro V 15 Gaming Laptop",
    brand: "Acer",
    category: "Gaming Laptops",
    description:
      "Value-focused gaming machine built for esports and daily use, with modern graphics and fast storage for responsive performance.",
    price: 89990,
    currency: "INR",
    discountPrice: 82990,
    images: [
      "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Intel Core i5-13420H" },
      { key: "Graphics", value: "NVIDIA GeForce RTX 4050 6GB" },
      { key: "Memory", value: "16GB DDR5 RAM" },
      { key: "Storage", value: "512GB NVMe SSD" },
      { key: "Display", value: "15.6-inch FHD 144Hz" },
    ],
    rating: 4.3,
    reviewCount: 1108,
    buyLinks: [
      { label: "Flipkart", url: "https://www.flipkart.com/" },
      { label: "Acer Store", url: "https://store.acer.com/en-in/" },
    ],
    source: "Acer Store",
    stockStatus: "in_stock",
    tags: ["gaming", "budget", "nitro", "rtx4050"],
  },
  {
    title: "Dell G15 5530 Gaming Laptop",
    brand: "Dell",
    category: "Gaming Laptops",
    description:
      "Gaming-focused laptop with a sturdy chassis, roomy keyboard deck, and enough power for AAA gaming at high settings.",
    price: 119990,
    currency: "INR",
    discountPrice: 111490,
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Intel Core i7-13650HX" },
      { key: "Graphics", value: "NVIDIA GeForce RTX 3050 6GB" },
      { key: "Memory", value: "16GB DDR5 RAM" },
      { key: "Storage", value: "1TB SSD" },
      { key: "Display", value: "15.6-inch FHD 120Hz" },
    ],
    rating: 4.2,
    reviewCount: 536,
    buyLinks: [
      { label: "Dell", url: "https://www.dell.com/en-in" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Dell",
    stockStatus: "limited_stock",
    tags: ["gaming", "dell", "g15", "intel"],
  },
  {
    title: "Apple MacBook Air M3 13-inch",
    brand: "Apple",
    category: "Office Laptops",
    description:
      "Thin and silent productivity laptop with excellent battery life, premium build quality, and fast performance for office and study workflows.",
    price: 114900,
    currency: "INR",
    discountPrice: 109900,
    images: [
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Apple M3" },
      { key: "Memory", value: "16GB Unified Memory" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "13.6-inch Liquid Retina" },
      { key: "Battery Life", value: "Up to 18 hours" },
    ],
    rating: 4.8,
    reviewCount: 2194,
    buyLinks: [
      { label: "Apple", url: "https://www.apple.com/in/" },
      { label: "Reliance Digital", url: "https://www.reliancedigital.in/" },
    ],
    source: "Apple",
    stockStatus: "in_stock",
    tags: ["office", "macbook", "lightweight", "battery-life"],
  },
  {
    title: "Dell Inspiron 14 5430",
    brand: "Dell",
    category: "Office Laptops",
    description:
      "Everyday productivity laptop with a comfortable keyboard, modern Intel processor, and dependable battery backup for hybrid work.",
    price: 67990,
    currency: "INR",
    discountPrice: 62990,
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484417894907-623942c8ee29?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Intel Core i5-1335U" },
      { key: "Memory", value: "16GB DDR5 RAM" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "14-inch FHD+" },
      { key: "Weight", value: "1.59 kg" },
    ],
    rating: 4.3,
    reviewCount: 418,
    buyLinks: [
      { label: "Dell", url: "https://www.dell.com/en-in" },
      { label: "Croma", url: "https://www.croma.com/" },
    ],
    source: "Dell",
    stockStatus: "in_stock",
    tags: ["office", "inspiron", "portable", "student"],
  },
  {
    title: "Lenovo ThinkPad E14 Gen 5",
    brand: "Lenovo",
    category: "Office Laptops",
    description:
      "Business-oriented laptop with a legendary keyboard, durable chassis, and enterprise-ready reliability for everyday professional use.",
    price: 74990,
    currency: "INR",
    discountPrice: 69990,
    images: [
      "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "AMD Ryzen 5 7530U" },
      { key: "Memory", value: "16GB DDR4 RAM" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "14-inch WUXGA IPS" },
      { key: "Security", value: "Fingerprint Reader" },
    ],
    rating: 4.5,
    reviewCount: 367,
    buyLinks: [
      { label: "Lenovo", url: "https://www.lenovo.com/in/en/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Lenovo",
    stockStatus: "in_stock",
    tags: ["office", "thinkpad", "business", "durable"],
  },
  {
    title: "HP Pavilion 14 Office Laptop",
    brand: "HP",
    category: "Office Laptops",
    description:
      "Slim and reliable office laptop with a bright display, quality webcam, and fast SSD storage for meetings and multitasking.",
    price: 62999,
    currency: "INR",
    discountPrice: 58999,
    images: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Processor", value: "Intel Core i5-1235U" },
      { key: "Memory", value: "16GB DDR4 RAM" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "14-inch FHD IPS" },
      { key: "Battery Life", value: "Up to 10 hours" },
    ],
    rating: 4.2,
    reviewCount: 529,
    buyLinks: [
      { label: "HP Online Store", url: "https://www.hp.com/in-en/shop/" },
      { label: "Flipkart", url: "https://www.flipkart.com/" },
    ],
    source: "HP Online Store",
    stockStatus: "in_stock",
    tags: ["office", "pavilion", "remote-work", "fhd"],
  },
  {
    title: "iPhone 15 128GB",
    brand: "Apple",
    category: "Phones",
    description:
      "Flagship iPhone with Dynamic Island, excellent cameras, smooth performance, and dependable battery life for everyday premium use.",
    price: 79900,
    currency: "INR",
    discountPrice: 74900,
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "6.1-inch Super Retina XDR" },
      { key: "Processor", value: "A16 Bionic" },
      { key: "Storage", value: "128GB" },
      { key: "Camera", value: "48MP Main + 12MP Ultra Wide" },
      { key: "Battery", value: "Up to 20 hours video playback" },
    ],
    rating: 4.8,
    reviewCount: 3145,
    buyLinks: [
      { label: "Apple", url: "https://www.apple.com/in/" },
      { label: "Flipkart", url: "https://www.flipkart.com/" },
    ],
    source: "Apple",
    stockStatus: "in_stock",
    tags: ["phone", "iphone", "ios", "camera"],
  },
  {
    title: "Samsung Galaxy S24 256GB",
    brand: "Samsung",
    category: "Phones",
    description:
      "Compact Android flagship with a bright AMOLED screen, premium cameras, and strong all-day battery performance.",
    price: 74999,
    currency: "INR",
    discountPrice: 69999,
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "6.2-inch Dynamic AMOLED 2X 120Hz" },
      { key: "Processor", value: "Exynos 2400" },
      { key: "Storage", value: "256GB" },
      { key: "Camera", value: "50MP Triple Camera" },
      { key: "Battery", value: "4000mAh" },
    ],
    rating: 4.6,
    reviewCount: 1859,
    buyLinks: [
      { label: "Samsung", url: "https://www.samsung.com/in/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Samsung",
    stockStatus: "in_stock",
    tags: ["phone", "android", "amoled", "flagship"],
  },
  {
    title: "OnePlus 12 256GB",
    brand: "OnePlus",
    category: "Phones",
    description:
      "Performance-oriented flagship with a fast display, premium design, rapid charging, and Hasselblad-tuned cameras.",
    price: 64999,
    currency: "INR",
    discountPrice: 61999,
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "6.82-inch QHD+ LTPO AMOLED 120Hz" },
      { key: "Processor", value: "Snapdragon 8 Gen 3" },
      { key: "Storage", value: "256GB UFS 4.0" },
      { key: "Camera", value: "50MP Triple Camera" },
      { key: "Charging", value: "100W SUPERVOOC" },
    ],
    rating: 4.7,
    reviewCount: 1273,
    buyLinks: [
      { label: "OnePlus", url: "https://www.oneplus.in/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "OnePlus",
    stockStatus: "in_stock",
    tags: ["phone", "oneplus", "fast-charging", "flagship"],
  },
  {
    title: "Google Pixel 8 128GB",
    brand: "Google",
    category: "Phones",
    description:
      "Clean Android smartphone with advanced computational photography, a compact design, and long software support.",
    price: 75999,
    currency: "INR",
    discountPrice: 70999,
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "6.2-inch Actua OLED 120Hz" },
      { key: "Processor", value: "Google Tensor G3" },
      { key: "Storage", value: "128GB" },
      { key: "Camera", value: "50MP Main + 12MP Ultra Wide" },
      { key: "Software", value: "7 years of updates" },
    ],
    rating: 4.5,
    reviewCount: 804,
    buyLinks: [
      { label: "Flipkart", url: "https://www.flipkart.com/" },
      { label: "Reliance Digital", url: "https://www.reliancedigital.in/" },
    ],
    source: "Flipkart",
    stockStatus: "limited_stock",
    tags: ["phone", "pixel", "camera", "android"],
  },
  {
    title: "Xiaomi 14 512GB",
    brand: "Xiaomi",
    category: "Phones",
    description:
      "Compact premium Android phone with Leica optics, a crisp AMOLED display, and top-tier Snapdragon performance.",
    price: 69999,
    currency: "INR",
    discountPrice: 65999,
    images: [
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1510557880182-3b7f18a7d7d9?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "6.36-inch AMOLED 120Hz" },
      { key: "Processor", value: "Snapdragon 8 Gen 3" },
      { key: "Storage", value: "512GB" },
      { key: "Camera", value: "Leica 50MP Triple Camera" },
      { key: "Battery", value: "4610mAh" },
    ],
    rating: 4.4,
    reviewCount: 612,
    buyLinks: [
      { label: "Mi Store", url: "https://www.mi.com/in/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Mi Store",
    stockStatus: "in_stock",
    tags: ["phone", "xiaomi", "leica", "flagship"],
  },
  {
    title: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    category: "Headphones",
    description:
      "Premium noise-cancelling headphones with detailed sound, powerful ANC, and long battery life for work and travel.",
    price: 29990,
    currency: "INR",
    discountPrice: 26990,
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Type", value: "Over-Ear Wireless" },
      { key: "Noise Cancellation", value: "Active Noise Cancellation" },
      { key: "Battery Life", value: "Up to 30 hours" },
      { key: "Connectivity", value: "Bluetooth 5.2" },
      { key: "Weight", value: "250 g" },
    ],
    rating: 4.8,
    reviewCount: 2306,
    buyLinks: [
      { label: "Sony", url: "https://www.sony.co.in/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Sony",
    stockStatus: "in_stock",
    tags: ["headphones", "anc", "wireless", "premium"],
  },
  {
    title: "Bose QuietComfort Ultra Headphones",
    brand: "Bose",
    category: "Headphones",
    description:
      "High-end wireless headphones with excellent comfort, immersive audio, and class-leading noise cancellation for commuting and focus.",
    price: 34900,
    currency: "INR",
    discountPrice: 31900,
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580894908361-967195033215?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Type", value: "Over-Ear Wireless" },
      { key: "Noise Cancellation", value: "World-class ANC" },
      { key: "Battery Life", value: "Up to 24 hours" },
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Audio Feature", value: "Immersive Audio" },
    ],
    rating: 4.7,
    reviewCount: 968,
    buyLinks: [
      { label: "Bose", url: "https://www.boseapac.com/en_in/" },
      { label: "Croma", url: "https://www.croma.com/" },
    ],
    source: "Bose",
    stockStatus: "in_stock",
    tags: ["headphones", "bose", "anc", "travel"],
  },
  {
    title: "Sennheiser Momentum 4 Wireless",
    brand: "Sennheiser",
    category: "Headphones",
    description:
      "Audiophile-friendly wireless headphones with long battery life, refined tuning, and effective adaptive noise cancellation.",
    price: 27990,
    currency: "INR",
    discountPrice: 24990,
    images: [
      "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Type", value: "Over-Ear Wireless" },
      { key: "Battery Life", value: "Up to 60 hours" },
      { key: "Noise Cancellation", value: "Adaptive ANC" },
      { key: "Connectivity", value: "Bluetooth 5.2" },
      { key: "Codec Support", value: "aptX Adaptive" },
    ],
    rating: 4.6,
    reviewCount: 741,
    buyLinks: [
      { label: "Amazon", url: "https://www.amazon.in/" },
      { label: "Headphone Zone", url: "https://www.headphonezone.in/" },
    ],
    source: "Headphone Zone",
    stockStatus: "in_stock",
    tags: ["headphones", "sennheiser", "anc", "battery-life"],
  },
  {
    title: "JBL Live 770NC Wireless Headphones",
    brand: "JBL",
    category: "Headphones",
    description:
      "Feature-rich wireless headphones with punchy sound, adaptive noise cancellation, and multi-device support at a mid-range price.",
    price: 14999,
    currency: "INR",
    discountPrice: 12999,
    images: [
      "https://images.unsplash.com/photo-1505740106531-4243f3831c78?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Type", value: "Over-Ear Wireless" },
      { key: "Battery Life", value: "Up to 65 hours" },
      { key: "Noise Cancellation", value: "True Adaptive ANC" },
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Mic", value: "4 Beamforming Mics" },
    ],
    rating: 4.3,
    reviewCount: 1184,
    buyLinks: [
      { label: "JBL", url: "https://in.jbl.com/" },
      { label: "Flipkart", url: "https://www.flipkart.com/" },
    ],
    source: "JBL",
    stockStatus: "in_stock",
    tags: ["headphones", "jbl", "wireless", "midrange"],
  },
  {
    title: "Apple Watch Series 9 GPS",
    brand: "Apple",
    category: "Smart Watches",
    description:
      "Premium smartwatch with advanced health tracking, smooth performance, and tight iPhone integration for fitness and productivity.",
    price: 41900,
    currency: "INR",
    discountPrice: 38900,
    images: [
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "Always-On Retina Display" },
      { key: "Case Size", value: "45mm" },
      { key: "Sensors", value: "ECG, Heart Rate, Blood Oxygen" },
      { key: "Battery Life", value: "Up to 18 hours" },
      { key: "Water Resistance", value: "50 meters" },
    ],
    rating: 4.8,
    reviewCount: 1638,
    buyLinks: [
      { label: "Apple", url: "https://www.apple.com/in/" },
      { label: "Croma", url: "https://www.croma.com/" },
    ],
    source: "Apple",
    stockStatus: "in_stock",
    tags: ["smartwatch", "apple", "fitness", "premium"],
  },
  {
    title: "Samsung Galaxy Watch 6 Classic",
    brand: "Samsung",
    category: "Smart Watches",
    description:
      "Stylish Wear OS smartwatch with a rotating bezel, vibrant display, sleep tracking, and strong Android integration.",
    price: 36999,
    currency: "INR",
    discountPrice: 32999,
    images: [
      "https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "1.5-inch Super AMOLED" },
      { key: "Case Size", value: "47mm" },
      { key: "OS", value: "Wear OS Powered by Samsung" },
      { key: "Sensors", value: "BioActive Sensor" },
      { key: "Battery Life", value: "Up to 40 hours" },
    ],
    rating: 4.5,
    reviewCount: 904,
    buyLinks: [
      { label: "Samsung", url: "https://www.samsung.com/in/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Samsung",
    stockStatus: "in_stock",
    tags: ["smartwatch", "wearos", "samsung", "fitness"],
  },
  {
    title: "Garmin Venu 3",
    brand: "Garmin",
    category: "Smart Watches",
    description:
      "Fitness-first smartwatch with precise tracking, AMOLED display, long battery life, and strong recovery and training insights.",
    price: 46990,
    currency: "INR",
    discountPrice: 43990,
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "1.4-inch AMOLED" },
      { key: "Battery Life", value: "Up to 14 days" },
      { key: "GPS", value: "Built-in Multi-GNSS" },
      { key: "Health Tracking", value: "Body Battery, Sleep Coach" },
      { key: "Water Rating", value: "5 ATM" },
    ],
    rating: 4.7,
    reviewCount: 447,
    buyLinks: [
      { label: "Garmin", url: "https://www.garmin.com/en-IN/" },
      { label: "Tata Cliq", url: "https://www.tatacliq.com/" },
    ],
    source: "Garmin",
    stockStatus: "limited_stock",
    tags: ["smartwatch", "fitness", "garmin", "gps"],
  },
  {
    title: "Amazfit GTR 4",
    brand: "Amazfit",
    category: "Smart Watches",
    description:
      "Stylish smartwatch with robust health tracking, built-in GPS, and multi-day battery life for everyday wellness use.",
    price: 16999,
    currency: "INR",
    discountPrice: 14999,
    images: [
      "https://images.unsplash.com/photo-1579586337278-3f436f25d4d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Display", value: "1.43-inch AMOLED" },
      { key: "Battery Life", value: "Up to 14 days" },
      { key: "GPS", value: "Dual-band Circularly Polarized GPS" },
      { key: "Sports Modes", value: "150+ workout modes" },
      { key: "Calls", value: "Bluetooth Calling" },
    ],
    rating: 4.3,
    reviewCount: 1122,
    buyLinks: [
      { label: "Amazon", url: "https://www.amazon.in/" },
      { label: "Amazfit", url: "https://in.amazfit.com/" },
    ],
    source: "Amazfit",
    stockStatus: "in_stock",
    tags: ["smartwatch", "gps", "battery-life", "fitness"],
  },
  {
    title: "Keychron K2 Pro Wireless Mechanical Keyboard",
    brand: "Keychron",
    category: "Keyboards",
    description:
      "Compact wireless mechanical keyboard with hot-swappable switches, Mac and Windows support, and premium typing feel.",
    price: 10999,
    currency: "INR",
    discountPrice: 9999,
    images: [
      "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Layout", value: "75%" },
      { key: "Connection", value: "Bluetooth / USB-C" },
      { key: "Switch Type", value: "Mechanical Hot-Swappable" },
      { key: "Backlight", value: "RGB" },
      { key: "Battery", value: "4000mAh" },
    ],
    rating: 4.7,
    reviewCount: 722,
    buyLinks: [
      { label: "Keychron", url: "https://keychron.in/" },
      { label: "Meckeys", url: "https://www.meckeys.com/" },
    ],
    source: "Keychron",
    stockStatus: "in_stock",
    tags: ["keyboard", "mechanical", "wireless", "productivity"],
  },
  {
    title: "Logitech MX Keys S",
    brand: "Logitech",
    category: "Keyboards",
    description:
      "Premium low-profile keyboard with smart backlighting, quiet keys, and multi-device support for office and creative workflows.",
    price: 12495,
    currency: "INR",
    discountPrice: 11495,
    images: [
      "https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Layout", value: "Full Size" },
      { key: "Connection", value: "Bluetooth / Logi Bolt USB" },
      { key: "Switch Type", value: "Low-profile Scissor Keys" },
      { key: "Backlight", value: "Smart Backlit Keys" },
      { key: "Battery", value: "Up to 10 days with backlight" },
    ],
    rating: 4.8,
    reviewCount: 1318,
    buyLinks: [
      { label: "Logitech", url: "https://www.logitech.com/en-in" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Logitech",
    stockStatus: "in_stock",
    tags: ["keyboard", "office", "wireless", "premium"],
  },
  {
    title: "Razer BlackWidow V4 Pro",
    brand: "Razer",
    category: "Keyboards",
    description:
      "Gaming keyboard with tactile mechanical switches, customizable macro controls, and immersive RGB lighting.",
    price: 22999,
    currency: "INR",
    discountPrice: 20999,
    images: [
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Layout", value: "Full Size" },
      { key: "Connection", value: "Wired USB-C" },
      { key: "Switch Type", value: "Razer Green Mechanical Switches" },
      { key: "Backlight", value: "Per-key Chroma RGB" },
      { key: "Extras", value: "Command Dial and Macro Keys" },
    ],
    rating: 4.6,
    reviewCount: 334,
    buyLinks: [
      { label: "Razer", url: "https://www.razer.com/" },
      { label: "EliteHubs", url: "https://elitehubs.com/" },
    ],
    source: "Razer",
    stockStatus: "limited_stock",
    tags: ["keyboard", "gaming", "mechanical", "rgb"],
  },
  {
    title: "Royal Kludge RK84 Mechanical Keyboard",
    brand: "Royal Kludge",
    category: "Keyboards",
    description:
      "Hot-swappable compact mechanical keyboard with wireless connectivity and strong value for enthusiasts and coders.",
    price: 6999,
    currency: "INR",
    discountPrice: 5899,
    images: [
      "https://images.unsplash.com/photo-1595044426077-d36d9236d5fd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Layout", value: "75%" },
      { key: "Connection", value: "Bluetooth / 2.4GHz / USB-C" },
      { key: "Switch Type", value: "Hot-Swappable Mechanical" },
      { key: "Backlight", value: "RGB" },
      { key: "Battery", value: "3750mAh" },
    ],
    rating: 4.4,
    reviewCount: 1209,
    buyLinks: [
      { label: "Meckeys", url: "https://www.meckeys.com/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "Meckeys",
    stockStatus: "in_stock",
    tags: ["keyboard", "mechanical", "budget", "wireless"],
  },
  {
    title: "LG UltraGear 27GR75Q 27-inch Monitor",
    brand: "LG",
    category: "Monitors",
    description:
      "27-inch QHD gaming monitor with fast IPS panel, 165Hz refresh rate, and excellent motion clarity for gaming and productivity.",
    price: 28999,
    currency: "INR",
    discountPrice: 25999,
    images: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Screen Size", value: "27-inch" },
      { key: "Resolution", value: "2560 x 1440" },
      { key: "Panel", value: "IPS" },
      { key: "Refresh Rate", value: "165Hz" },
      { key: "Response Time", value: "1ms" },
    ],
    rating: 4.6,
    reviewCount: 896,
    buyLinks: [
      { label: "LG", url: "https://www.lg.com/in/" },
      { label: "Amazon", url: "https://www.amazon.in/" },
    ],
    source: "LG",
    stockStatus: "in_stock",
    tags: ["monitor", "gaming", "qhd", "165hz"],
  },
  {
    title: "Dell UltraSharp U2723QE 27-inch Monitor",
    brand: "Dell",
    category: "Monitors",
    description:
      "Professional 4K monitor with accurate colors, USB-C connectivity, and a versatile ergonomic stand for productivity-heavy setups.",
    price: 58999,
    currency: "INR",
    discountPrice: 54999,
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496171367470-9ed9a91ea931?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Screen Size", value: "27-inch" },
      { key: "Resolution", value: "3840 x 2160" },
      { key: "Panel", value: "IPS Black" },
      { key: "Refresh Rate", value: "60Hz" },
      { key: "Connectivity", value: "USB-C Hub, HDMI, DisplayPort" },
    ],
    rating: 4.8,
    reviewCount: 302,
    buyLinks: [
      { label: "Dell", url: "https://www.dell.com/en-in" },
      { label: "Croma", url: "https://www.croma.com/" },
    ],
    source: "Dell",
    stockStatus: "limited_stock",
    tags: ["monitor", "4k", "professional", "usb-c"],
  },
  {
    title: "Samsung Odyssey G5 32-inch Monitor",
    brand: "Samsung",
    category: "Monitors",
    description:
      "Immersive curved gaming monitor with QHD resolution, 165Hz refresh rate, and strong contrast for cinematic gameplay.",
    price: 30999,
    currency: "INR",
    discountPrice: 27999,
    images: [
      "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516383740770-fbcc5ccbece0?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Screen Size", value: "32-inch" },
      { key: "Resolution", value: "2560 x 1440" },
      { key: "Panel", value: "VA Curved" },
      { key: "Refresh Rate", value: "165Hz" },
      { key: "Response Time", value: "1ms" },
    ],
    rating: 4.4,
    reviewCount: 711,
    buyLinks: [
      { label: "Samsung", url: "https://www.samsung.com/in/" },
      { label: "Flipkart", url: "https://www.flipkart.com/" },
    ],
    source: "Samsung",
    stockStatus: "in_stock",
    tags: ["monitor", "gaming", "curved", "qhd"],
  },
  {
    title: "BenQ GW2780 27-inch Monitor",
    brand: "BenQ",
    category: "Monitors",
    description:
      "Affordable office monitor with thin bezels, eye-care features, and reliable IPS visuals for work-from-home setups.",
    price: 14990,
    currency: "INR",
    discountPrice: 12990,
    images: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: [
      { key: "Screen Size", value: "27-inch" },
      { key: "Resolution", value: "1920 x 1080" },
      { key: "Panel", value: "IPS" },
      { key: "Refresh Rate", value: "60Hz" },
      { key: "Eye Care", value: "Low Blue Light, Flicker-Free" },
    ],
    rating: 4.5,
    reviewCount: 1934,
    buyLinks: [
      { label: "Amazon", url: "https://www.amazon.in/" },
      { label: "BenQ", url: "https://www.benq.com/en-in/" },
    ],
    source: "BenQ",
    stockStatus: "in_stock",
    tags: ["monitor", "office", "ips", "budget"],
  },
];
